[build]
  publish = "."
  functions = "netlify/functions"

[[redirects]]
  from = "/api/test-argyle"
  to = "/.netlify/functions/test-argyle"
  status = 200

[[redirects]]
  from = "/api/test-finicity"
  to = "/.netlify/functions/test-finicity"
  status = 200

[[redirects]]
  from = "/api/test-truv"
  to = "/.netlify/functions/test-truv"
  status = 200

[[redirects]]
  from = "/api/test-accountchek"
  to = "/.netlify/functions/test-accountchek"
  status = 200
